# docker-compose.yml
# version: '3.8'

# --- Networks for Security Isolation ---
networks:
  # 1. External/Frontend Network (For 'app' and 'pgadmin' to be accessible)
  frontend-network:
    driver: bridge
  # 2. Internal/Backend Network (For 'cognitive-engine', 'db', 'ollama', and 'message-broker' - THE SECURE NETWORK)
  core-network:
    driver: bridge

# --- Volumes for Persistent Data ---
volumes:
  dev_postgres_data:
  prod_postgres_data:
  pgadmin_data:
  ollama_models:
  open_webui_data:

# --- Services Definitions ---
services:
  # 1. DEVELOPMENT DATABASE (Postgres + pgvector)
  dev_db:
    # Service Name: dev_db
    container_name: dev_db
    image: pgvector/pgvector:pg16
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - core-network
    profiles:
      - dev
    restart: always

  # 2. PRODUCTION DATABASE (Postgres + pgvector)
  prod_db:
    # Service Name: prod_db
    container_name: prod_db
    image: pgvector/pgvector:pg16
    env_file:
      - .env.prod
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - core-network
    profiles:
      - prod
    restart: always

  # 3.REDIS (Message Broker)
  # FIXED: Explicitly named service 'message-broker' to match documentation.
  message-broker:
    container_name: message-broker
    image: redis:latest
    networks:
      - core-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 4. DEVELOPMENT APPLICATION SERVICE (The Body - Public API)
  dev_app:
    # Service Name: dev_app
    container_name: dev_app
    build:
      context: .
      dockerfile: Dockerfile.app # <-- NOW USES THE MINIMAL APP-ONLY IMAGE
    env_file:
      - .env.dev
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - message-broker
      - dev_engine
    networks:
      - frontend-network # User access
      - core-network # Database/Engine access
    profiles:
      - dev
    restart: always

  # 5. DEVELOPMENT COGNITIVE ENGINE (Brain API - LLM & DB Logic)
  dev_engine:
    # Service Name: dev_engine
    container_name: dev_engine
    build:
      context: .
      dockerfile: Dockerfile.engine # <-- NOW USES THE FULL ENGINE IMAGE
    env_file:
      - .env.dev
    command: gunicorn engine.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.00.0.0:8001
    depends_on:
      - dev_db
      - ollama
      - message-broker # CRITICAL ADDITION
    networks:
      - core-network
    profiles:
      - dev
    restart: always

  # 6. PRODUCTION APPLICATION SERVICE (The Body)
  prod_app:
    # Service Name: prod_app
    container_name: prod_app
    build:
      context: .
      dockerfile: Dockerfile.app # <-- NOW USES THE MINIMAL APP-ONLY IMAGE
    env_file:
      - .env.prod
    command: gunicorn app.main:app -w 8 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - message-broker
      - prod_engine
    networks:
      - frontend-network
      - core-network
    profiles:
      - prod
    restart: always

  # 7. PRODUCTION COGNITIVE ENGINE (Brain API)
  prod_engine:
    # Service Name: prod_engine
    container_name: prod_engine
    build:
      context: .
      dockerfile: Dockerfile.engine # <-- NOW USES THE FULL ENGINE IMAGE
    env_file:
      - .env.prod
    command: gunicorn engine.main:app -w 8 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8001
    depends_on:
      - prod_db
      - ollama
      - message-broker
    networks:
      - core-network
    profiles:
      - prod
    restart: always

  # 8. MAINTENANCE SERVICE (NEW - For Privileged Cron Jobs) 🚨
  # Mandated by the Data Retention Standard (04 standards guide.md)
  maintenance-service:
    container_name: maintenance-service
    env_file:
      - .env.dev
    # Use the Engine image as it requires the privileged full DB role and all dependencies
    build:
      context: .
      dockerfile: Dockerfile.engine
    depends_on:
      - dev_db
    # CRITICAL: No exposed ports. Only on the secure core-network.
    networks:
      - core-network
    profiles:
      - dev
    restart: "no" # This is a job, not a continuously running server
    # Entrypoint to run the nightly purge script (Example path)
    command: python /usr/src/app/engine/maintenance/run_purge_cron.py

  # 9. PGADMIN (DB Admin Tool)
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env.dev
      - .env.prod # Allow both for flexibility
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - frontend-network
    restart: unless-stopped

  # 10. OLLAMA (Local LLM Engine)
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    # CRITICAL ADDITION: Pull the necessary model on startup for the engine to function.
    # The Engine is assumed to be configured to use the 'mistral' model.
    # FIX: Set the entrypoint to /bin/sh to ensure the command is run as a shell script
    # entrypoint: /bin/sh
    # FIX: Use -c to pass the multi-step command to the shell
    # command: -c "ollama serve & sleep 5 && ollama pull mistral && wait"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - core-network
    restart: unless-stopped

  # 11. AI WEB UI (Open WebUI)
  open_webui:
    container_name: open_webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "3000:8080"
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - core-network
      - frontend-network
    restart: always
